heroiclabs/nakama-docs

- docs/install-docker-quickstart.md
I think `--db` might come from the previous release. Replaced with `--database.address` so that future user following this tutorial won't be running into problems
> fixed incorrect key for docker command

- docs/gameplay-leaderboards.md
Under Submit a score. All of the operator examples INResultSet are result. This makes the example not compile. They should be list. Also, it follows the consistency of the other examples.
> Fixed result set variable name

- docs/storage-collections.md
In C#, the field "Data" for a record doesn't exist. I think that this is meant to be "Value".
> Fix for typo

- docs/runtime-code-basics.md
There was a runtime error when returning the payload from the pokemon.lua function get_pokemon, returning a json object to the client fixes this issue.
> "Runtime function returned invalid data" error when returning payload.

- docs/social-realtime-chat.md
C# doesn't have type-inferred constants, so I fixed some spots where there was uncompilable code.
> Fix social-realtime-chat.md typos (.NET & Unity)

- docs/social-in-app-notifications.md
The docs say the notification codes can be greater than or equal to 0, but the actual implementation has a check for <= 0. Assuming the implementation is correct, the docs should be updated. I'm not sure if notification code 0 is actually used for anything by default, though.
runtime_lua_nakama.go
```lua
code := l.CheckInt(4)
if code <= 0 {
l.ArgError(4, "expects code to number above 0")
return 0
}
```
runtime_go_nakama.go
```go
if notification.Code <= 0 {
return errors.New("expects code to number above 0")
}
```
> Notification codes must be greater than zero

- docs/runtime-code-basics.md
Fixed some broken links, typos, and minor grammar things in the runtime basics documentation.
In the case of "api.proto" and "realtime.proto", I saw that they were both removed and replaced(?) by "apigrpc.proto", so I updated that accordingly. Do let me know if that's not the correct file. Thanks!
> Fix broken links + typos

- docs/storage-access-controls.md
In the Lua example of "Object ownership" o.Value needs to be changed to o.value for it to work
> Lua convention is lower-case fields

- docs/advanced-streams.md
- docs/authentication.md
- docs/gameplay-leaderboards.md
- docs/gameplay-matchmaker.md
- docs/gameplay-multiplayer-realtime.md
- docs/gameplay-tournaments.md
- docs/godot-client-guide.md
- docs/runtime-code-basics.md
- docs/social-friends.md
- docs/social-groups-clans.md
- docs/social-in-app-notifications.md
- docs/social-realtime-chat.md
- docs/social-status.md
- docs/storage-access-controls.md
- docs/storage-collections.md
- docs/user-accounts.md
Would have been nice if GDscript was supported by `mkdocs`. Github does, there is probably a file for that. Need to investigate.
Note:
Godot does not allow code outside functions (only variable definitions), and sockets need to be created as node variables (or they will disconnect when they go out if scope, this is pretty common behaviour, I hope it's clear enough in this examples, I also updated the client guide).
**Note 2: Some inconsistencies/bugs I found when testing the snippets with Nakama 2.11.0**
- `list_notifications_async` always returns a cursor, even when the notification list is empty.
This means we can't check if the cursor is null, but have to check if the list is empty to know when we fetched all the notifications.
- The `tournament` endpoint …
> Godot example code.

- docs/runtime-code-basics.md
Hi, thank you for your work on the project. 😍
It's helped me a lot while I'm building something with it.
There has an error "type error is not an expression" when building Go code in a provided example.
Only changing "error" to "err" will fix the issue.
- https://heroiclabs.com/docs/runtime-code-basics/#an-example-module
> Fix typo in an "An example module" of Go "Runtime Code Basics" docs.

- README.md
- mkdocs.yml
Closes #146 
In our 4.x version, I saw buggy-looking radio buttons locally as our code tabs. I assume we override the .css for those in a private Heroic Labs website repo.
In 5.x, the code tabs look locally as they do in the publicly hosted site, which leads me to believe some bugs were fixed with their theming.
Upgrade guide listed here: https://squidfunk.github.io/mkdocs-material/releases/5/
Once I'm onboarded in the next week or two I can test on Google Cloud.
> Upgrade to mkdocs 1.1.2 and mkdocs-material 5.3.0

- docs/install-configuration.md
- docs/runtime-code-basics.md
Was getting an error in one of the `nakama-js` tests due to a mismatched default HTTP runtime key. If/when we accept this I can update the JS SDK and any other erroneous SDK test suites.
See what nakama actually uses as a default here: https://github.com/heroiclabs/nakama/blob/master/server/config.go#L651
> Fix documentation of default http runtime key to match go code

- docs/runtime-code-basics.md
Refactored "<some formatted string":format(values...) to be string.format("<formatted string>", values, ...)
The LUA interpreter that comes with Nakama is not supporting the former syntax, however the latter works and is standard Lua.
> Refactored the Lua formatted strings in examples

- docs/cocos2d-x-js-client-guide.md
- docs/javascript-client-guide.md
I noticed when using the Javascript SDK that the `Client` constructor accepts `port` as a string, not a number.
I assume the cocos2d-x-js client also uses the same code, so I updated that documentation as well.
> document 'port' argument as a string when passed to js client

- docs/install-docker-quickstart.md
I thought this was causing version conflicts, but it seems not. Would it be best to increment the version in the docs, or remove the version entirely maybe?
> Update Nakama image version in example docker-compose

- docs/runtime-code-function-reference.md
Documentation typo on lua functions tournament_create
endTime -> end_time
> Fix typo on lua nk.tournament_create

- docs/gameplay-multiplayer-realtime.md
problem:
> ![image](https://user-images.githubusercontent.com/27877342/98724455-bd3c1a80-23ce-11eb-9124-11b74f7f6344.png)
> put space in "join a match" .NET tab

- docs/gameplay-tournaments.md
Removed an unreferenced local variable and fixed the naming of another local variable in the example for creating a tournament.
> Fix the Lua example for creating a tournament.

- docs/gameplay-tournaments.md
Lua table indices start at 1.  This fixes the error, "attempt to index a non-table object(nil)".
> Fix the Lua example for distributing tournament rewards.

- docs/android-java-client-guide.md
- docs/cocos2d-x-client-guide.md
- docs/cocos2d-x-js-client-guide.md
- docs/cpp-client-guide.md
- docs/defold-client-guide.md
- docs/godot-client-guide.md
- docs/javascript-client-guide.md
- docs/swift-ios-client-guide.md
- docs/unity-client-guide.md
- docs/unreal-client-guide.md
Improved the consistency of the descriptions for the events in the Handle Events section of the Client Guides.
eg)
"It handles join and leave events within chat."
is now:
"Receives join and leave events within chat."
Which more closely resembles the other descriptions. This improves readability.
> Improved consistency of language in Client Guides' Handle Events section

- docs/gameplay-matchmaker.md
At least `joinMatch(token)` gave me some "incorrect match id" errors.
In my minified JS nakama-js version first joinMatch argument is match_id and the second one is token_id.
`joinMatch(null, token)` worked for my case, so I guess the problem is just in docs?
> Fix joinMatch JS invocation from matchmaker docs

- docs/runtime-code-function-reference.md
`nakama/runtime` seems to no longer exist, so `https://github.com/heroiclabs/nakama/blob/master/runtime/runtime.go` ends up returning a 404 rather than the function list. I've fixed it to point to `https://github.com/heroiclabs/nakama/blob/master/server/runtime.go` instead.
> Fix 404 in runtime function reference
